version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-compose
    image: flask-app
    container_name: api_service
    command: ["flask", "run", "--host=0.0.0.0", "--port=5000", "--reload"]
    ports:
      - 5000:5000
    expose:
      - 5000
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - db
      - redis
    networks:
      - backend
  db:
    image: postgres:latest
#    restart: always
    container_name: postgres_database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myDB
#      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
#      POSTGRES_INITDB_ARGS: --auth-host=scram-sha-256
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis
    container_name: redis_cluster
#    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
#    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81
    volumes:
      - redis_data:/data
    networks:
      - backend

volumes:
  pg_data:
    driver: local
  redis_data:
    driver: local

networks:
  backend:
    driver: bridge